package com.vanghar.xdbc.api;

import java.sql.Connection;
import java.sql.SQLException;

// FIXME - addition of enums for int types
public interface DbConnection
    extends Connection
{
    DbStatement createStatement() throws SQLException;
    DbStatement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException;
    DbStatement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
            throws SQLException;

    // These 3 should have been implemented in JDBC in the first place
    DbStatement createStatement(String sql) throws SQLException;
    DbStatement createStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;
    DbStatement createStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
            throws SQLException;
    
    PreparedDbStatement prepareStatement(String sql) throws SQLException;
    PreparedDbStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;
    PreparedDbStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
            int resultSetHoldability) throws SQLException;
    PreparedDbStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
    PreparedDbStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException;
    PreparedDbStatement prepareStatement(String sql, String[] columnNames) throws SQLException;

    CallableDbStatement prepareCall(String sql) throws SQLException;
    CallableDbStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;
    CallableDbStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
            throws SQLException;

    CallableDbStatement prepareProc(DbProcedure proc) throws SQLException;
    CallableDbStatement prepareProc(DbProcedure proc, int resultSetType, int resultSetConcurrency) throws SQLException;
    CallableDbStatement prepareProc(DbProcedure proc, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
            throws SQLException;
}
